# Generated by Django 4.2.16 on 2024-09-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True)),
                ('type', models.UUIDField(db_index=True)),
                ('subtype', models.UUIDField(db_index=True)),
                ('reading', models.BigIntegerField(db_index=True)),
                ('location', models.UUIDField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
